# Workflow for pulling in TBill Data from the Alpha Vantage API
apiVersion: argoproj.io/v1alpha1
kind: cronWorkflow
metadata:
  name: alpha-vantage-2yr-tbill
  namespace: argo
spec:
  schedule: "0 */12 * * *"
  timezone: "America/Los_Angeles"
  startingDeadlineSeconds: 0
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  suspend: false
  workflowSpec:
    entrypoint: load-two-year-bond-data
    imagePullSecrets:
    - name: docker-creds
    templates:
      - name: load-two-year-bond-data
        nodeSelector:
          k3s_role: x86_worker
        container:
          image: markhamlee/alphavantage_tbill_interval:latest
          command: ["python3"]
          args: ["/etl/main.py", "Alpha Vantage 2 Year TBill. Scheduled on: {{workflow.scheduledTime}}"]
          resources: 
            limits:
              memory: 256Mi
              cpu: 200m
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: pg-secrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secrets
          - name: ALERT_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_ETL_ALERTS
                name: slack-webhook-pipeline-failures
          - name: ALPHA_KEY
            valueFrom:
              secretKeyRef:
                key: ALPHA_KEY
                name: etl-secrets-data
          - name: DASHBOARD_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DASHBOARD_DB
                name: postgres-etl-config
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB_HOST
                name: postgres-config
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: postgres-config
          - name: BOND_MATURITY
            value: 2year
          - name: TBILL_TABLE
            value: two_year_tbill
          - name: COUNT
            value: "7"