services:
  cyberpowerpc_pfc1500_ups:
    dockerfile: IoT/cyberpowerpc_pfc1500_ups/Dockerfile
    image: markhamlee/cyberpowerpc_pfc1500_ups
    path: IoT/cyberpowerpc_pfc1500_ups
    version: 1.8.1
  dependabot_agent:
    dockerfile: ai_agents/dependabot_agent/Dockerfile
    image: markhamlee/dependabot_agent
    path: ai_agents/dependabot_agent
    version: 1.5.2
  dependabot_data_ingestion:
    dockerfile: ai_agents/dependabot_data_ingestion/Dockerfile
    image: markhamlee/dependabot_data_ingestion
    path: ai_agents/dependabot_data_ingestion
    version: 1.5.2
  kasa_smart_plug:
    dockerfile: IoT/kasa_smart_plug/Dockerfile
    image: markhamlee/kasa_smart_plug
    path: IoT/kasa_smart_plug
    version: 2.1.2
  sds011_air_quality_sensor:
    dockerfile: IoT/sds011_air_quality_sensor/Dockerfile
    image: markhamlee/sds011_air_quality_sensor
    path: IoT/sds011_air_quality_sensor
    version: 1.9.2
  site_monitor_agent:
    dockerfile: ai_agents/site_monitor_agent/Dockerfile
    image: markhamlee/site_monitor_agent
    path: ai_agents/site_monitor_agent
    version: 1.4.2
  site_monitor_data_ingestion:
    dockerfile: ai_agents/site_monitor_data_ingestion/Dockerfile
    image: markhamlee/site_monitor_data_ingestion
    path: ai_agents/site_monitor_data_ingestion
    version: 1.4.0
  site_monitor_reminder_service:
    dockerfile: ai_agents/site_monitor_reminder_service/Dockerfile
    image: markhamlee/site_monitor_reminder_service
    path: ai_agents/site_monitor_reminder_service
    version: 1.2.2
