# Workflow for pulling in task data from Asana
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: asana-tasks-homelab-2025
  namespace: argo
spec:
  schedule: "0 * * * *"
  timezone: "America/Los_Angeles"
  startingDeadlineSeconds: 0
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  suspend: false
  workflowSpec:
    entrypoint: asana-tasks-homelab-2025
    imagePullSecrets:
    - name: docker-creds
    templates:
      - name: asana-tasks-homelab-2025
        nodeSelector:
          k3s_role: x86_worker
        container:
          image: markhamlee/asanadata:latest
          command: ["python3"]
          args: ["/etl/main.py", "Asana task data ETL. Scheduled on: {{workflow.scheduledTime}}"]
          resources: 
            limits:
              memory: 256Mi
              cpu: 200m
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: pg-secrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: pg-secrets
          - name: ALERT_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_ETL_ALERTS
                name: slack-webhook-pipeline-failures
          - name: ASANA_KEY
            valueFrom:
              secretKeyRef:
                key: ASANA_KEY
                name: etl-secrets-data
          - name: DASHBOARD_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DASHBOARD_DB
                name: asana-etl-variables
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB_HOST
                name: postgres-config
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: postgres-config
          - name: ASANA_TABLE
            valueFrom:
              configMapKeyRef:
                key: HOMELAB_Q1_2025_TABLE
                name: asana-etl-variables
          - name: GID
            valueFrom:
              configMapKeyRef:
                key: HOMELAB_Q1_2025_GID
                name: asana-etl-variables