# Argo Workflow for pulling in stock data from the Finnhub API
# Nodejs variant
apiVersion: argoproj.io/v1alpha1
kind: cronWorkflow
metadata:
  name: finnhub-stock-price-etl-nodejs
  namespace: argo
spec:
  schedule: "*/15 * * * *"
  timezone: "America/Los_Angeles"
  startingDeadlineSeconds: 0
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  suspend: false
  workflowSpec:
    entrypoint: load-stock-data
    imagePullSecrets:
    - name: docker-secrets
    templates:
      - name: load-stock-data
        node_selector:
          node_type: etl_node_arm64
        container:
          image: markhamlee/finnhub_stockprice_nodejs:latest
          command: ["node"]
          args: ["/app/finnhub_nodejs/src/index.js", "Finnhub Stock API. Scheduled on: {{workflow.scheduledTime}}"]
          resources: 
            limits:
              memory: 256Mi
              cpu: 200m
          env:
          - name: INFLUX_KEY
            valueFrom:
              secretKeyRef:
                key: PROD_INFLUX_KEY
                name: influxdb-secret
          - name: ALERT_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_ETL_ALERTS
                name: slack-webhook-pipeline-failures
          - name: FINNHUB_SECRET
            valueFrom:
              secretKeyRef:
                key: FINNHUB_SECRET
                name: finnhub-secret-key
          - name: INFLUX_ORG
            valueFrom:
              configMapKeyRef:
                key: INFLUX_ORG
                name: key-etl-variables
          - name: INFLUX_URL
            valueFrom:
              configMapKeyRef:
                key: INFLUX_URL
                name: key-etl-variables
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                key: BUCKET
                name: key-etl-variables
          - name: FINNHUB_MEASUREMENT_SPY
            value: finnhub_quotes
          - name: STOCK_SYMBOL
            value: SPY