apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-mki
  labels:
    app: airflow-logs-mki
spec:
  storageClassName: longhorn
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-logs-mki
    namespace: airflow
  hostPath:
    path: /tmp/data/