# Workflow for pulling in GitHub dependabot alert data
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dependabot-alert-status-data-platform
  namespace: argo
spec:
  schedule: "0 * * * *"
  timezone: "America/Los_Angeles"
  startingDeadlineSeconds: 0
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  suspend: false
  workflowSpec:
    entrypoint: dependabot-alert-status-data-platform
    imagePullSecrets:
    - name: docker-creds
    templates:
      - name: dependabot-alert-status-data-platform
        node_selector:
          k3s_role: x86_worker
        container:
          image: "markhamlee/github_dependabot_agent_data"
          command: ["python3"]
          args: ["/etl/main.py", "GitHub Dependabot Alert Status Scheduled on: {{workflow.scheduledTime}}"]
          resources: 
            limits:
              memory: 256Mi
              cpu: 200m
          env:
          - name: ALERT_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_ETL_ALERTS
                name: slack-webhook-pipeline-failures
          - name: SECURITY_SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: SECURITY_SLACK_WEBHOOK
                name: slack-github-alerts       
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                key: GITHUB_TOKEN
                name: github-api-token    
          - name: ALERTS_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: ALERTS_ENDPOINT
                name: github-variables
          - name: GITHUB_API_BASE_URL
            valueFrom:
              configMapKeyRef:
                key: GITHUB_BASE_URL
                name: github-variables
          - name: REPO_BASE
            valueFrom:
              configMapKeyRef:
                key: REPO_BASE
                name: github-variables  
          - name: POSTGRES_DEPENDABOT_DATABASE
            valueFrom:
              secretKeyRef:
                key: DEPENDABOT_ALERT_DATABASE
                name: dependabot-postgres-data
          - name: DEPENDABOT_AGENT_POSTGRES
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DEPENDABOT_SECRET
                name: dependabot-postgres-data          
          - name: POSTGRES_USER_DEPENDABOT
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DEPENDABOT_USER
                name: dependabot-postgres-data        
          - name: POSTGRES_HOST_K3S
            valueFrom:
              secretKeyRef:
                key: POSTGRES_HOST
                name: dependabot-postgres-data  
          - name: DEPENDABOT_ALERT_STATUS_TABLE
            valueFrom:
              secretKeyRef:
                key: DEPENDABOT_ALERT_STATUS_TABLE
                name: dependabot-postgres-data  
          - name: REPO_NAME
            value: internet-and-iot-data-platform 
          - name: GITHUB_PIPELINE_NAME
            value: dependabot_alerts_data_platform
          - name: REPO_SHORT_NAME
            value: data_platform