name: asana_image_build_build

on:
  push:
    branches:
      - "main"
    paths:
      - "etl_pipelines/etl_library/*"
      - "etl_pipelines/asana/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./etl_pipelines/
          file: ./etl_pipelines/asana/Dockerfile
          platforms: linux/amd64
          push: true
          tags: markhamlee/asanadata:latest