name: Automated Container Redeployment via Portainer API

on:
  push:
    branches:
      - "main"
    paths:
      - "cicd_pipeline_automation/docker_common/*"
      - "cicd_pipeline_automation/portainer_common/*"
      - "cicd_pipeline_automation/cicd_common/*"
      - "cicd_pipeline_automation/portainer_automated_redeployment/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./cicd_pipeline_automation/
          file: ./cicd_pipeline_automation/portainer_automated_redeployment/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: markhamlee/portainer_redeployment:latest