name: Tailscale Node MOnitoring

on:
  push:
    branches:
      - "main"
    paths:
      - "network_management/network_monitoring_libraries/*"
      - "network_management/tailscale_device_status/*"
      - "network_management/tailscale_library/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./network_management/
          file: ./network_management/tailscale_device_status/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: markhamlee/tailscale_device_monitoring:latest